### ISSUE TITLE
Bug: opc.connect() and opc.servers() not working with host besides localhost

### ISSUE THREAD

**Issue by jamesbraza** [ya-mouse/openopc#25]
I have the OpenOPC Gateway Service running locally.  I have validated client-server connectivity for `localhost` using [MatrikonOPC Simulation Server](https://www.matrikonopc.com/products/opc-drivers/opc-simulation-server.aspx). 🥳

Now, I am trying to connect across the network to an OPC DA server on another host (`10.4.8.71`).  I have the following script to make that happen:

```python
import OpenOPC

  opc = OpenOPC.open_client("localhost")  # Succeeds
 opc.connect(opc_server="Matrikon.OPC.Simulation", opc_host="10.4.8.71")  # Fails 
```

When run, it throws the following `Pyro4.errors.SerializeError`:

```python
Traceback (most recent call last):
  File "C:\path\to\venv\lib\site-packages\Pyro4\core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "C:\path\to\venv\lib\site-packages\Pyro4\core.py", line 467, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "C:\path\to\venv\lib\site-packages\Pyro4\util.py", line 171, in deserializeData
    return self.loads(data)
  File "C:\path\to\venv\lib\site-packages\Pyro4\util.py", line 614, in loads
    return self.recreate_classes(serpent.loads(data))
  File "C:\path\to\venv\lib\site-packages\Pyro4\util.py", line 416, in recreate_classes
    return self.dict_to_class(literal)
  File "C:\path\to\venv\lib\site-packages\Pyro4\util.py", line 633, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "C:\path\to\venv\lib\site-packages\Pyro4\util.py", line 395, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: OpenOPC.OPCError
```

Furthermore, trying to run:

```python
import OpenOPC

  opc = OpenOPC.open_client("localhost")  # Succeeds
 opc.servers(opc_host="10.4.8.71")  # Fails 
```

I get the same stack trace.  An aside is it would be good to add support for `Pyro4` serialization of `OpenOPC.OPCError`.

Now debugging inside the `OpenOPC.OPCError` to see the real `Exception`:

```python
>>> print("".join(data["attributes"]["_pyroTraceback"]))
Traceback (most recent call last):
  File "OpenOPC.py", line 1117, in servers
  File "C:\path\to\AppData\Local\Temp\tmph013js_3\gen_py\F8582D24-88FB-11D0-B850-00C0F0104305x0x1x0.py", line 239, in GetOPCServers
    return self._ApplyTypes_(1610743825, 1, (12, 0), ((12, 17),), 'GetOPCServers', None,Node
  File "win32com\client\__init__.py", line 572, in _ApplyTypes_
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147467259), None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "Pyro4\core.py", line 1424, in handleRequest
  File "OpenOPC.py", line 1123, in servers
OpenOPC.OPCError: servers: -2147467259
```

Here's some related issues/posts:
- https://github.com/sightmachine/OpenOPC/issues/6
- https://github.com/sightmachine/OpenOPC/issues/11
- https://sourceforge.net/p/openopc/discussion/709251/thread/3da622a7c3/

What might I be doing wrong?

Alternately, I believe OpenOPC may have some bug such that it doesn't work if the OPC host is not `localhost`.

---

**Machine Set Up**

I have Windows Firewall turned off on both machines, and the OPC Gateway Service running on the local machine (and not on the remote machine `10.4.8.71`).  Also, I have run `regsvr32 /s \path\to\openopc\lib\gbda_aut.dll` on both machines.

I am using Python 3.10.9-win32 from [`pyenv-win`](https://github.com/pyenv-win/pyenv-win)

**Comment by jamesbraza** [comment]
Okay so I realized from [this comment](https://github.com/ya-mouse/openopc/issues/24#issuecomment-1386208778) that I misunderstood where software entities should live.

Closing this in favor of https://github.com/ya-mouse/openopc/issues/26, which has a different stack trace.
